export const productFields = [
  {
    id: 01,
    category: "Clothing",
    subcategories: [
      {
        gender: ["Male", "Female", "Everyone"],
      },
      {
        style: [
          "Dresses",
          "Leggings",
          "Mini Skirt",
          "Sweatshirts & Hoodies",
          "T-Shirts",
          "Tank Tops",
        ],
      },
    ],
  },
  {
    id: 02,
    category: "Phone Cases",
    subcategories: [
      {
        type: ["All", "iPhone", "Samsung"],
      },
    ],
  },
  {
    id: 03,
    category: "Stickers",
    subcategories: [],
  },
  {
    id: 04,
    category: "Wall Art",
    subcategories: [
      "Art Board Prints",
      "Art Prints",
      "Canvas Prints",
      "Framed Prints",
      "Metal Prints",
      "Photogenic Prints",
      "Posters",
    ],
  },
  {
    id: 05,
    category: "Home & Living",
    subcategories: [
      "Acrylic Blocks",
      "Bedding",
      "Clocks",
      "Magnets",
      "Mugs",
      "Pillows & Cushions",
      "Tapestries",
    ],
  },
  {
    id: 06,
    category: "Stationery & Office",
    subcategories: [
      "Greeting Cards",
      "Hardcover Journals",
      "Postcards",
      "Spiral Notebooks",
    ],
  },
  {
    id: 07,
    category: "Accessories",
    subcategories: [
      "Backpacks",
      "Drawstring Bags",
      "Scarves",
      "Socks",
      "Tote Bags",
      "Water Bottles",
      "Zipper Pouches",
      "Tech Accessories",
    ],
  },
];

export const products = [
  {
    0: {
      id: "01",
      category: "Clothing",
      subcategory: "Dresses",
      name: "Wilderness Fitness Graphic Dress",
      price: 4531,
      imageMain: "",
      colors: {},
      description:
        "A cool graphic of a weightlifter with a frame pack loaded up with a set of elk antlers, standing in front of a pine forest.",
    },
    1: {
      id: "02",
      category: "Clothing",
      subcategory: "Leggings",
      name: "Wilderness Fitness Leggings",
      price: 4510,
      imageMain: "",
      colors: {},
      description:
        "A cool graphic of a weightlifter with a frame pack loaded up with a set of elk antlers, standing in front of a pine forest.",
    },
    2: {
      id: "03",
      category: "Clothing",
      subcategory: "Mini Skirts",
      name: "Still Breathing Mini Skirt",
      price: 3434,
      imageMain: "",
      colors: {},
      description:
        'Nothing can keep me down. A graphic of a mountain range with trees behind and "Still Breathing" in the forefront.',
    },
    3: {
      id: "04",
      category: "Clothing",
      subcategory: "Sweatshirts & Hoodies",
      name: "Crossed Antlers Logo Lightweight Hoodie",
      price: 3988,
      imageMain: "",
      colors: {
        Black: "#000",
        "Heather Grey": "#7e7e7e",
        "Charcoal Heather": "#323232",
        "Royal Heather": "#576d9f",
        Navy: "#21233c",
        "Denim Heather": "#484854",
      },
      description: "Crossed antlers logo",
    },
    4: {
      id: "05",
      category: "Clothing",
      subcategory: "T-Shirts",
      name: "Arrow Splatter Essential T-Shirt",
      price: 1984,
      imageMain: "",
      colors: {
        Black: "#000",
        White: "#fafafa",
        "Charcoal Heather": "#323232",
        "Heather Grey": "#7e7e7e",
        "Dark Blue": "#322e3f",
        Blue: "#353d77",
        "Light Blue": "#9ec0d5",
        Yellow: "#edbb3b",
        Creme: "#e5d6c5",
        "Light Grey": "#e0e1dd",
        Eggplant: "#462445",
        Red: "#dd2121",
        "Dark Red": "#5a1f32",
        Army: "#403c32",
        "Dark Grey": "#5e504c",
        Green: "#026541",
        "Moss Green": "#575734",
        Brown: "#33281f",
      },
      description: "Triple arrow logo with gradient splatter",
    },
    5: {
      id: "06",
      category: "Clothing",
      subcategory: "Tank Tops",
      name: "You Know What It Is - Racerback Tank Top",
      price: 2232,
      imageMain: "",
      colors: {
        Black: "#000",
        White: "#fafafa",
        "Dark Blue": "#322e3f",
      },
      description: "Yellow logo and arrow",
    },
    6: {
      id: "07",
      category: "Phone Cases",
      subcategory: "iPhone",
      name: "Far Blue Mountains iPhone Tough Case",
      price: 3467,
      imageMain: "",
      colors: {},
      description: "Original acrylic on canvas of mountains",
    },
    7: {
      id: "08",
      category: "Phone Cases",
      subcategory: "Samsung Cases",
      name: "Splatter Logo Blue/Yellow - Samsung Case",
      price: 2380,
      imageMain: "",
      colors: {},
      description: "Triple arrow logo splatter yellow blue gradient",
    },
  },
];
